package com.example.projeto.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import java.util.HashMap;
import java.util.Map;

@Controller
@RequestMapping("/")
public class SearchController {
    @GetMapping("/pesquisa")
    public String pesquisa() {
        return "pesquisa/index";
    }

    private final Map<String, String> capitals = new HashMap<String, String>() {{
        put("afeganistão", "Cabul");
        put("albânia", "Tirana");
        put("argélia", "Argel");
        put("samoa americana", "Pago Pago");
        put("andorra", "Andorra-a-Velha");
        put("angola", "Luanda");
        put("anguilla", "The Valley");
        put("antígua e barbuda", "Saint John's");
        put("argentina", "Buenos Aires");
        put("armênia", "Erevã");
        put("aruba", "Oranjestad");
        put("austrália", "Canberra");
        put("áustria", "Viena");
        put("azerbaijão", "Baku");
        put("bahamas", "Nassau");
        put("barein", "Manama");
        put("bangladesh", "Daca");
        put("barbados", "Bridgetown");
        put("bielorrússia", "Minsk");
        put("bélgica", "Bruxelas");
        put("belize", "Belmopã");
        put("benin", "Porto Novo");
        put("bermudas", "Hamilton");
        put("butão", "Timbu");
        put("bolívia", "La Paz");
        put("bósnia e herzegovina", "Saraievo");
        put("botsuana", "Gaborone");
        put("brasil", "Brasília");
        put("território britânico do oceano índico", "Diego Garcia");
        put("ilhas virgens britânicas", "Road Town");
        put("brunei", "Bandar Seri Begauã");
        put("bulgária", "Sófia");
        put("burkina faso", "Uagadugu");
        put("mianmar", "Nepiédue");
        put("burundi", "Bujumbura");
        put("camboja", "Pnom Pene");
        put("camarões", "Iaundé");
        put("canadá", "Otava");
        put("cabo verde", "Praia");
        put("ilhas cayman", "George Town");
        put("república centro-africana", "Bangui");
        put("chade", "N'Djamena");
        put("chile", "Santiago");
        put("china", "Pequim");
        put("colômbia", "Bogotá");
        put("comores", "Moroni");
        put("república democrática do congo", "Quinxassa");
        put("república do congo", "Brazavile");
        put("ilhas cook", "Avarua");
        put("costa rica", "São José");
        put("costa do marfim", "Iamussucro");
        put("croácia", "Zagrebe");
        put("cuba", "La Habana");
        put("chipre", "Nicósia");
        put("república tcheca", "Praga");
        put("dinamarca", "Copenhague");
        put("djibuti", "Djibuti");
        put("dominica", "Roseau");
        put("república dominicana", "Santo Domingo");
        put("timor-leste", "Díli");
        put("egito", "Cairo");
        put("el salvador", "San Salvador");
        put("inglaterra", "Londres");
        put("equador", "Quito");
        put("guiné equatorial", "Malabo");
        put("eritreia", "Asmara");
        put("estônia", "Talin");
        put("etiópia", "Adis Abeba");
        put("ilhas malvinas", "Porto Stanley");
        put("ilhas faroé", "Torshavn");
        put("fiji", "Suva");
        put("finlândia", "Helsinque");
        put("frança", "Paris");
        put("polinésia francesa", "Papeete");
        put("gabão", "Libreville");
        put("gâmbia", "Banjul");
        put("geórgia", "Tbilisi");
        put("alemanha", "Berlim");
        put("gana", "Acra");
        put("gibraltar", "Gibraltar");
        put("grã-bretanha", "Atenas");
        put("grécia", "Nuuk");
        put("groenlândia", "Saint George's");
        put("granada", "Hagatna");
        put("guam", "Cidade da Guatemala");
        put("guatemala", "Saint Peter Port");
        put("guernsey", "Conacri");
        put("guiné", "Bissau");
        put("guiné-bissau", "Georgetown");
        put("guiana", "Porto Príncipe");
        put("haiti", "Porto Príncipe");
        put("honduras", "Tegucigalpa");
        put("hong kong", "Hong Kong");
        put("hungria", "Budapeste");
        put("islândia", "Reiquiavique");
        put("índia", "Nova Délhi");
        put("indonésia", "Jacarta");
        put("irã", "Teerã");
        put("iraque", "Bagdá");
        put("irlanda", "Dublin");
        put("ilha de man", "Douglas");
        put("israel", "Jerusalém");
        put("itália", "Roma");
        put("jamaica", "Kingston");
        put("japão", "Tóquio");
        put("jersey", "Saint Helier");
        put("jordânia", "Amã");
        put("cazaquistão", "Astana");
        put("quênia", "Nairobi");
        put("kiribati", "Taraua");
        put("kuwait", "Cidade do Kuwait");
        put("quirguistão", "Bisqueque");
        put("laos", "Vientiane");
        put("letônia", "Riga");
        put("líbano", "Beirute");
        put("lesoto", "Maseru");
        put("libéria", "Monróvia");
        put("líbia", "Trípoli");
        put("liechtenstein", "Vaduz");
        put("lituânia", "Vilnius");
        put("luxemburgo", "Luxemburgo");
        put("macau", "N/A");
        put("macedônia", "Skopje");
        put("madagascar", "Antananarivo");
        put("malawi", "Lilongue");
        put("malásia", "Kuala Lumpur");
        put("maldivas", "Malé");
        put("mali", "Bamaco");
        put("malta", "La Valeta");
        put("ilhas marshall", "Majuro");
        put("martinica", "Fort-de-France");
        put("mauritânia", "Nuakchote");
        put("maurício", "Porto Luís");
        put("méxico", "Cidade do México");
        put("micronésia", "Paliquir");
        put("moldávia", "Quixinau");
        put("mônaco", "Mônaco");
        put("mongólia", "Ulan Bator");
        put("montserrat", "Plymouth");
        put("marrocos", "Rabate");
        put("moçambique", "Maputo");
        put("namíbia", "Windhoek");
        put("nauru", "Iaren");
        put("nepal", "Catmandu");
        put("holanda", "Amsterdã");
        put("antilhas holandesas", "Willemstad");
        put("nova zelândia", "Wellington");
        put("nicarágua", "Manágua");
        put("níger", "Niamei");
        put("nigéria", "Abuja");
        put("niue", "Alofi");
        put("ilha norfolk", "Kingston");
        put("ilhas marianas do norte", "Saipan");
        put("coreia do norte", "Pionguiangue");
        put("noruega", "Oslo");
        put("omã", "Mascate");
        put("paquistão", "Islamabade");
        put("palau", "Melequeoque");
        put("panamá", "Cidade do Panamá");
        put("papua-nova guiné", "Porto Moresby");
        put("paraguai", "Assunção");
        put("peru", "Lima");
        put("filipinas", "Manila");
        put("ilhas pitcairn", "Adamstown");
        put("polônia", "Varsóvia");
        put("portugal", "Lisboa");
        put("porto rico", "San Juan");
        put("catar", "Doha");
        put("romênia", "Bucareste");
        put("rússia", "Moscou");
        put("ruanda", "Quigali");
        put("santa helena", "Jamestown");
        put("saint kitts e nevis", "Basseterre");
        put("santa lúcia", "Castries");
        put("saint pierre e miquelon", "Saint-Pierre");
        put("saint vicent e granadinas", "Kingstown");
        put("samoa", "Apia");
        put("são marino", "São Marino");
        put("são tomé e príncipe", "São Tomé");
        put("arábia saudita", "Riade");
        put("escócia", "Edimburgo");
        put("senegal", "Dacar");
        put("sérvia e montenegro", "Belgrado");
        put("seicheles", "Victoria");
        put("serra leoa", "Freetown");
        put("cingapura", "Cingapura");
        put("eslováquia", "Bratislava");
        put("eslovênia", "Liubliana");
        put("ilhas salomão", "Honiara");
        put("somália", "Mogadíscio");
        put("áfrica do sul", "Pretória");
        put("geórgia do sul", "King Edward Point");
        put("coreia do sul", "Seul");
        put("espanha", "Madri");
        put("sri lanka", "Colombo");
        put("sudão", "Cartum");
        put("suriname", "Paramaribo");
        put("suazilândia", "Mbabane");
        put("suécia", "Estocolmo");
        put("suíça", "Berna");
        put("síria", "Damasco");
        put("taiwan", "Taipé");
        put("tajiquistão", "Duchambé");
        put("tanzânia", "Dares Salã");
        put("tailândia", "Bangcoc");
        put("tibete", "Lassa");
        put("togo", "Lomé");
        put("tonga", "Nucualofa");
        put("trindade e tobago", "Porto de Espanha");
        put("tunísia", "Tunes");
        put("turquia", "Ancara");
        put("turcomenistão", "Asgabate");
        put("ilhas turcas e caicos", "Grand Turk");
        put("tuvalu", "Funafuti");
        put("uganda", "Campala");
        put("ucrânia", "Quieve");
        put("emirados árabes unidos", "Abu Dhabi");
        put("uruguai", "Montevidéu");
        put("estados unidos", "Washington");
        put("uzbequistão", "Tashkent");
        put("vanuatu", "Porto Vila");
        put("cidade do vaticano", "Cidade do Vaticano");
        put("venezuela", "Caracas");
        put("vietnã", "Hanói");
        put("ilhas virgens", "Charlotte Amalie");
        put("país de gales", "Cardife");
        put("wallis e futuna", "Mata-Utu");
        put("iêmen", "Saná");
        put("zâmbia", "Lusaca");
        put("zimbábue", "Harare");
    }};

    @PostMapping("/pesquisar")
    public String pesquisar(Model model, String country1, String country2) {
        String capital1 = capitals.get(country1.toLowerCase());
        String capital2 = capitals.get(country2.toLowerCase());
        if (capital1 == null)
            capital1 = "Capital não encontrada para o país: " + country1;

        if (capital2 == null)
            capital2 = "Capital não encontrada para o país:" + country2;

        model.addAttribute("country1", country1);
        model.addAttribute("country2", country2);
        model.addAttribute("capital1", capital1);
        model.addAttribute("capital2", capital2);
        return "pesquisa/pesquisar";
    }
}